WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

number = @{ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
name  = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

// Operators
eq  = { "=" }
ne = { "!=" }
le = { "<=" }
lt  = { "<" }
ge = { ">=" }
gt  = { ">" }
logic_op = _{ eq | ne | le | lt | ge | gt }


add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }
pow = { "^" }
arith_op = _{ add | sub | mul | div | pow }

arrow = { "->" }

binfix = _{ arrow | arith_op }

neg = { "-" }
prefix = _{ slate | neg }

factorial = { "!" }
slatom = { name ~ ":" ~ expr }
slate = { "(" ~ (slatom ~ ("," ~ slatom)*) ~ ")" }
postfix = _{ slate | factorial }

// Primaries are the base elements
circle = { "circle" ~ "(" ~ "x" ~ ":"  ~ expr ~ "," ~ "y" ~ ":" ~ expr ~ "," ~ "r" ~ ":" ~ expr ~ ")" }
question = { "?" }
primary = _{ circle | number | name | "(" ~ expr ~ ")" | question }

// The exact flat structure the Pest Pratt parser expects
secondary = _{ prefix* ~ primary ~ postfix* }
expr = { secondary ~ (binfix ~ secondary)* }
train = { expr ~ (logic_op ~ expr)* }

line_withouteoi = { train }
line = _{ SOI ~ line_withouteoi ~ EOI }