WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

number = @{ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
name  = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

// Operators
add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }
pow = { "^" }
arith_op = _{ add | sub | mul | div | pow }

eq  = { "=" }
ne = { "!=" }
le = { "<=" }
lt  = { "<" }
ge = { ">=" }
gt  = { ">" }
logic_op = _{ eq | ne | le | lt | ge | gt }

arrow = { "->" }

infix = _{ arrow | arith_op | logic_op }

neg = { "-" }
slatom = { name ~ "=" ~ expr }
slate = { "[" ~ (slatom ~ ("," ~ slatom)*) ~ "]" }
prefix = _{ slate | neg }

factorial = { "!" }
call = { "(" ~ (expr ~ ("," ~ expr)*) ~ ")" }
postfix = _{ call | factorial }

// Primaries are the base elements
circle = { "circle(" ~ (expr ~ ("," ~ expr)*)? ~ ")" }
primary = _{ circle | number | name | "(" ~ expr ~ ")" }

// The exact flat structure the Pest Pratt parser expects
secondary = _{ prefix* ~ primary ~ postfix* }
expr = { secondary ~ (infix ~ secondary)* }

line = _{ SOI ~ expr ~ EOI }